### ISSUE TITLE
How to set the label rotation bypass and if that can be copied to another network?

### ISSUE THREAD

**Issue by gmhhope** [cytoscape/py4cytoscape#111]
Hi Barry,

Sorry for bothering you these days. Could you provide me solutions to set the label rotation bypass? Additionally, if I have premade the rotation bypass, is there a way I can retrieve them using py4cytoscape and then copied those properties (the rotation levels) to another network? 

For example, I created a new network and used `layout_copycat` and set the style with the older one but it cannot inherit the node position (possibly any bypass properties)? In other words, I definitely had hard time to understand how the bypass properties related to the style. Will they get documented in the particular style or they remained separate properties isolated from a particular style?

I looked forward to any of your suggestions! Thanks for being so helpful these couples of days/weeks.

Thanks,
Minghao Gong

**Comment by gmhhope** [comment]
I just figured that out. The bypass is standalone properties which are isolated from style.

`p4c.get_node_property(visual_property='NODE_LABEL_ROTATION')` can retrieve all label rotations. And I can apply back by `p4c.set_node_property_bypass()`

**Comment by gmhhope** [comment]
```
NODE_FONT_FACE_PROPERTIES = {'NODE_LABEL_FONT_FACE'}
NODE_LABEL_PROPERTIES = {'NODE_LABEL'}
```
Does it mean this feature (`NODE_LABEL_POSITION` and `NODE_LABEL_ROTATION`) not yet supported in py4cytoscape? 

https://github.com/cytoscape/py4cytoscape/blob/645042fe4bd63e1ef5e9620fb4c9578b4bef63f7/py4cytoscape/style_visual_props.py#L29

**Comment by bdemchak** [comment]
Hi --

Getting the warning you're asking about doesn't mean that a property isn't supported ... it just means that there isn't a validation for the argument. So, the argument you supply will be used without checking it first.

Regarding the grouping of style values, bypasses and defaults, it's not so arbitrary as it might seem. Taking a look at the [py4cytoscape documentation](https://py4cytoscape.readthedocs.io/en/latest/), see the grouping of all of the style-related functions:

![image](https://github.com/cytoscape/py4cytoscape/assets/3696094/9c8dfaf4-4d70-44a4-b241-b925dd1dfa15)

This roughly tracks what the GUI Style Mapping panels are doing:

![image](https://github.com/cytoscape/py4cytoscape/assets/3696094/3642c730-ceae-4926-aeba-d904a36bd673)

The Default setting is the style value if there is no mapping or default style value.

The Mapping setting determines the style value based on a node or edge property.

The Bypass is pretty important to you because it applies a property to a particular node or edge instead of all nodes or edges, regardless of the Default or Mapping settings. You've been using it to set the node location, which is appropriate because each node has its own location.

Good to review the [Styles documentation for the GUI](http://manual.cytoscape.org/en/stable/Styles.html), especially the [How Mappings Section](http://manual.cytoscape.org/en/stable/Styles.html#how-mappings-work).

For reusing style Default or Mapping settings, you can define a style and name it (e.g., Test1) using either the GUI ("Create New Style" under the settings menu in the Style panel or via py4cytoscape's [Style Management functions](https://py4cytoscape.readthedocs.io/en/latest/reference/styles.html#style-management) ... and apply an existing style to a new network.

For reusing the bypass values, it's a little tricker. You're already using set_node_property_bypass() (or a variation) on a node-by-node basis. So, how to perform the equivalent of get_node_property_bypass(), which isn't provided in py4cytoscape? 

To know this, you might understand that py4cytoscape is a front end to Cytoscape's CyREST interface. set_node_property_bypass() resolves to the CyREST `PUT /v1/networks/{networkId}/views/{viewId}/{objectType}/{objectId}` function. You can see this by visiting the Help | Automation | CyREST API menu, which puts up a Swagger page. This function is in the Network View section. 

If you get that far, you might notice a corresponding `GET ` function. So, you can build your own get_node_property_bypass() by using the set_node_property_bypass() function to inform how you might call the corresponding `GET` function. You can learn more about this in the [Concepts](https://py4cytoscape.readthedocs.io/en/latest/concepts.html#missing-functions) documentation section.

Feel free to ask questions. Frankly, I think get_node_property_bypass() might be a good addition to the py4cytoscape/RCy3 API, but that won't happen quickly.

@AlexanderPico @yihangx

**Comment by gmhhope** [comment]
I have been working around this issue by just not going for circular visualization. Now I just would like to change all the default node label postion. But figure out there isn't such function? The closest one is `set_node_custom_position`, which seems not changing the labeling position but probably the customized graph position relative to the node. 

Could you help with that? I think I am closed to finish using this tool for my figure : ) Thanks always for all the help @bdemchak 

Best,
MG

**Comment by bdemchak** [comment]
Hi --

Please note that py4cytoscape 1.8 was released today, and it addresses some of the points you've raised. For new functions, I'm talking with the RCy3 people ... they're not in 1.8.

For information on 1.8, please see https://py4cytoscape.readthedocs.io/en/latest/release_log.html#py4cytoscape-1-8-0

**Comment by bdemchak** [comment]
Regarding the default node label position, can you send me a screenshot showing a poorly positioned label and indicating where you'd like the label to be instead??  Thanks!

**Comment by gmhhope** [comment]
Sorry for the late comment.

<img width="168" alt="Screenshot 2023-07-23 at 2 37 37 PM" src="https://github.com/cytoscape/py4cytoscape/assets/12982817/ec0a4b05-c0f8-4093-a0b0-9f6e1f2e19b8">
Just position like this. I meant I can easily do it in GUI. But I just cannot figure out how to do it in the python pkg.

Thanks,
Minghao

**Comment by bdemchak** [comment]
No problem... happy for the reply ... how would you do this with the GUI?

**Comment by gmhhope** [comment]
Here it is: see the label position screenshot: <img width="993" alt="Screenshot 2023-07-23 at 2 54 40 PM" src="https://github.com/cytoscape/py4cytoscape/assets/12982817/1bd94622-ff10-4d1d-8e1e-ab01d2d0092d">

**Comment by bdemchak** [comment]
Hi --

This was a wonderful question, and it caused me to do a little work because property values aren't documented anywhere.

The short answer:

`p4c.set_visual_property_default({'visualProperty': 'NODE_LABEL_POSITION', 'value':'N,S,c,10.00,20.00'}, 'default')`

So, the NODE_LABEL_POSITION property is a list of values that correspond to the dialog box fields. The field values appear to be Node Anchor Points, Label Anchor Points, Text Justification, X Offset, Y Offset.

So, 'N,S,c,10.00,20.00' would be North, South, Center Justified, X Offset 10, Y Offset 20.

How did I figure this out?? I used the Cytoscape GUI to dump the visual style to styles.xml ... the menu item is **File | Export | Styles to File...**, and I chose the name of the style being used for my network.

From there, I looked into styles.xml and found the NODE_LABEL_POSITION property:

`<visualProperty default="N,S,c,10.00,20.00" name="NODE_LABEL_POSITION"/>`

From there, the format of the property can be deduced.

Does this make sense to you, or should I go into more depth?

Note that you can set the default value (and other style information) by using the GUI and the dialog you showed me. Once you do that, you can save the whole style to styles.xml. You can use py4cytoscape to load the style:

`p4c.import_visual_styles()`

@AlexanderPico @yihangx

**Comment by gmhhope** [comment]
Hey Barry,

I don't mean to reply late. I was in a conference for a talk and then so many works afterwards. 

Thanks very much for this wonderful answer. I am coming back to this project and I just have another question that I will post in a separate issue.

Thanks again for the detailed answer!

Best,
Minghao Gong

**Comment by gmhhope** [comment]
Hi Barry,
