### ISSUE TITLE
get MCODE cluster network images

### ISSUE THREAD

**Issue by tyasird** [cytoscape/py4cytoscape#13]
Hi,

Firstly, Thanks for code tutorials.

Now I am able to run Mcode and to create clusters.
But I have some problems.

1) I want to create cluster Images but when I making a loop some images are missing. I think cytoscape working for other job and because of that it doesn't create all images. To solve this problem I have added timeout end of the loop but its making my script slowly. Is there any solution for this? If I would get the cytoscape job status then I can create new job.

2) Is there any other way to get all cluster network Images and tables at one time? I did in loop, is this the correct way? 

I added my code.

Thanks

             

	network_name = uuid.uuid4().hex
	network_suid = py4.networks.create_network_from_data_frames(
			edges=results, 
			title= network_name,
			collection= network_name + '_collection'
	)

	analyze = py4.commands.commands_post('analyzer/analyze')

	mcode = py4.commands.commands_post('mcode cluster degreeCutoff=2 fluff=false fluffNodeDensityCutoff=0.1 haircut=true includeLoops=false kCore=2 maxDepthFromStart=100 network=current nodeScoreCutoff=0.2 scope=NETWORK')

	big_clusters = [i for i in range(len(mcode['clusters'])) if len(mcode['clusters'][i]['nodes']) > 10]

	clusters = []
	for i in range(len(big_clusters)):

		view_id = py4.commands.commands_post('mcode view id=1 rank=' + str(i+1) )

		clusters.append( py4.tables.get_table_columns() \
					  .drop(columns=['id','name','selected','MCODE_Cluster','SUID']) \
					  .sort_values(by=['MCODE_Score'], ascending=False) \
					 .reset_index(drop=True) )
		
		py4.network_views.get_network_view_suid()
		img_name = uuid.uuid4().hex
		py4.export_image(str(img_name))
		Image(img_name+'.png')
		sleep(3)

**Comment by bdemchak** [comment]
Thanks for this report, Yasir …

 

I’m very happy to see that MCODE is working from py4cytoscape!

 

I’m very interested to get to the bottom of this, and would like to help you remove the sleep() from your loop. I think the problem may be a “race condition”, which is where Cytoscape starts a new operation before a previous operation is complete. 

 

Can you tell me which version of Cytoscape you’re using? As we discover race conditions, we have eliminated them from Cytoscape. 

 

There is a version that’s nearly ready for release, and which has some race conditions fixed. Would you mind trying it with your export code? 

https://cytoscape-builds.ucsd.edu/cytoscape-builds/Cytoscape-3.8.1/2020_08_14/

 

Would it be possible for you provide a copy of ‘results’ so we can try this code under the same conditions you’re running?

 

Thanks1

**Comment by bdemchak** [comment]
Hi, Yasir –

 

I checked this out using our Affinity Purification network sample, which is just a little complicated. I set a node threshold of 3 because my clusters were likely smaller than yours.

 

The race condition appears to be in the ‘mcode cluster’ command, which appears to be returning before all of the cluster views are created. Frankly, I’m not surprised, as I have seen Cytoscape return (in a different circumstance) before a view was completely created.

 

So, for your workflow, my solution was to insert a sleep(5) right after the ‘mcode cluster’ call. After that, the loop through the cluster ranks goes pretty quickly.

 

Does that help you out? (I have attached my test code in case it’s helpful)

 

Note that the ‘analyzer/analyze’ call isn’t needed here. You may think it is because the MCODE documentation refers to an analyze operation. In fact, that’s the ‘mcode cluster’ command itself.

 

Also, you don’t need the call to get_network_view_suid() in to code I have.

 

Let me know how this goes for you … I’m very glad you’re making progress.

**Comment by tyasird** [comment]
Sir,

Many Thanks for your attention and help.

As you say, I have inserted sleep() after the "mcode cluster" then it creates network images very quickly. It worked. (I tested on 10 networks.) 

Now I realised another problem for my case,
I have been creating web application which users can upload their own results. The problem is, when cytoscape running for other user I have to say cytoscape is busy. Therefore I need get cytoscape status, is it still running or not? So If cytoscape running for another job then I will show user to loading screen. Because I tried to run my code simultanisly and I got errors. 
I hope I could explain my question.


I forgot to add my code, sorry for that. I have attached my code and input data now.

Thanks

[py4.zip](https://github.com/bdemchak/py4cytoscape/files/5094689/py4.zip)

**Comment by bdemchak** [comment]
Hi, Yasir –

 

Thanks for the code. I have accepted your pull request and will likely reorganize the folder so tutorials are easier to find and are separate from each other. I can think of other users that would appreciate your effort.

 

Regarding your web application, I have seen something similar at Novartis in San Diego. Here are some things to consider:

 

Cytoscape is intended to run on behalf of a single user, and so the properties and defaults (e.g., default layout) are expected to be used by that one person. 

 

Py4cytoscape and Cytoscape assume there is one and only one call active at a time. There is no consideration of multi-threaded or queued request execution. 

 

Many useful workflows involve several Cytoscape steps.

 

The Novartis implementation accounted for all of this by creating a job queue, and users submit to it. A “job” involves running a workflow, starting with creating a new session, and ending with some output (… just like your workflow). The webapp shows a table of pending and completed jobs. When the job is complete, the results are added to the job entry in the “completed” table so the user can download them.

 

This design simulates a single user, one user after another. I think it calls CyREST directly because it was created before py4cytoscape was written. 

 

Considering that you’re creating UUID-based network and collection names, it seems like you’re hoping to use Cytoscape to simultaneously work on networks for different users. This depends on passing the “network=” parameter for each py4cytoscape call. This may work if each of the networks added together don’t exceed the total memory available to Cytoscape. It still requires, though, that all callers wait for any currently executing call to finish. That synchronization would need to be done at the webapp level, as there is no “busy” flag available in Cytoscape (so far). Such a flag may not be very useful, anyway, as it’s quite possible that two webapp copies could read the flag at the same time and conclude that Cytoscape was available, and then *both* submit requests to Cytoscape. It shouldn’t be too hard to create a flag on the webapp side … maybe using a lock file in /tmp or some other simple device.

 

Supposing this worked, the next issue would be stopping too many simultaneous users … Cytoscape’s memory is limited. If that’s an issue, you’d have to create a solution similar to Novartis’. And if you have that, it may be unnecessary to allow to users to use Cytoscape at the same time.

 

Does any of this make sense to you?? Have I missed the mark??

**Comment by tyasird** [comment]
Sir,

Thank you very much for your examples and explanatory information.

You have touched on all the important points.

This week, I want to focus on this issue and I hope I can handle it. (like Novartis style, in the light of the information you provide)

If I will able to achieve, definitly I'll let you know,

Thank you very much again.

**Comment by bdemchak** [comment]
Best of luck!

... sent from my mobile phone ... please forgive my typos.

**Comment by bdemchak** [comment]
Hi, Yasir …

 

The MCODE team has fixed the race condition that required the sleep(3). I’m posting it on my personal site rather than risk sending it via e-mail. Here it is: http://tpsoft.com/yasir/mcode-app-1.7.0.jar

 

Would you be interested in trying it out??

 

Thanks!

**Comment by tyasird** [comment]
Hi Barry,

I have just tried it and It's working perfectly. 

In the new version of MCODE they have changed clusters variables in table columns. It was MCODE_Clusters and MCODE_Score before but now it's MCODE::Clusters and MCODE::Score.

In addition, I figured out about multi use problem.

I haven't finished the web tool yet but the solution is like that,

I created 3 functions: create_session, get_session, delete_session

when the user start to analyze, I run create_session function and when it finishs I destroy session. In the same time if another use want to use cytoscape, I check the sesion with the CyREST API. If there is any session I show to waiting screen. It means cytoscape is busy. By the way, there isn't session query for CyREST Command API so I handle it with the CyREST API.

Many Thanks for helping me.




```
    def create_session(self):
        self.session_name = uuid.uuid4().hex
        py4.save_session(self.session_folder + self.session_name)
        return self.session_name

    def get_session(self):
        session_name = py4.commands.cyrest_get('session/name')
        return os.path.basename(session_name['name'])

    def delete_session(self):
        py4.session.close_session(False)
```

**Comment by bdemchak** [comment]
Hi, Yasir –

 

I’m very glad to see the progress you’re making! … and am very happy to see that you’re able to use CyREST directly.

 

Based on your feedback, I wrote a section in the py4cytoscape documentation regarding calling CyREST. If you find time, would you let me know what’s missing or incorrect? https://py4cytoscape.readthedocs.io/en/latest/concepts.html#missing-functions

 

Also, you are correct about the change in the MCODE column naming. The new scheme reflects an intent for all apps to eventually embed a namespace into the column name. That way, apps that use the same columns for different purposes won’t collide.

 

I am including Christian Lopes on this thread … he created the new MCODE. I think he may want to interact directly with you regarding his work and your need.

 

Very exciting progress … best of luck!

**Comment by chrtannus** [comment]
Hi, Yasir –

I had to make another modification to the column names.
Now all the MCODE columns have the **result number** as suffix, even the ones from cluster networks (i.e. the networks created through the command `mcode view`).
For instance, if the result id is **2**, then the MCODE columns are:
- MCODE::Clusters (2)
- MCODE::Score (2)
- MCODE::Node Status (2)

So your code should be something like this:
```
for i in range(len(big_clusters)):
            view_id = commands.commands_post('mcode view id=1 rank=' + str(i+1) )
            clusters.append( tables.get_table_columns()
                             .drop(columns=['id','name','selected','MCODE::Clusters (1)','SUID'])
                             .sort_values(by=['MCODE::Score (1)'], ascending=False)
                             .reset_index(drop=True) )
```

Sorry for yet another change, but I'm still working on a few minor issues before the final release.
However, I think these column names are final.

You can download the latest snapshot of the MCODE app here: https://www.dropbox.com/s/tgsqjx3smry301q/mcode-app-2.0.0-BETA.jar?dl=0

Please let me know if you have any issues or questions.

Thanks,
Christian Lopes

**Comment by tyasird** [comment]
Hi Barry,

Thanks for including Christian Lopes.
I have just read the documentation, it is very good and explanatory. It will definitly benefit for others.

Many thanks for your help, it means a lot to me.

**Comment by tyasird** [comment]
Hi  Christian,

Firstly thanks for the fix, when I was coding web-tool I realized that all cluster names are the same and I was thinking about it wouldn't good to shown users with the same titles. I am very happy due to this changes.  

Many thanks,
Yasir
