### ISSUE TITLE
node_name_to_node_suid() does not accept node name that is also a number

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#142]
Recent changes to py4cytoscape_utils functions greatly sped up function execution, and passed all formal tests.

However, a supplementary test fails when a node name (which is a string) actually contains only digits (e.g., '851303' instead of 'YBR043C'). 

![image](https://github.com/user-attachments/assets/113bcc8e-f3a0-4a2a-98b0-9d0e33b55a41)

This supplementary test is a Jupyter Notebook at [py4cytoscape\tests\Notebooks\Gang Su basic protocol 1.ipynb](https://github.com/cytoscape/py4cytoscape/blob/master/tests/Notebooks/Gang%20Su%20basic%20protocol%201.ipynb) in line #198.

To duplicate this, start execution at the first cell and wait about 10 minutes.

**Comment by GeneCodeSavvy** [comment]
The issue is caused by a conflict between the `normalize_list(item_names)` function and how keys are stored in the `item_name_to_suid_list` dictionary. Specifically, `normalize_list` is converting certain items, like the `query_node` '851303', into integers, while the `item_name_to_suid_list` dictionary keeps its keys as strings. This mismatch between integer and string types leads to key lookup failures.

To resolve this, we can modify the code that creates the dictionary to attempt to convert each key to an integer before adding it. This can be done by wrapping the conversion in a `try` and `except` block, so if the conversion fails, the key remains a string. Here's the modified code:

```python
item_name_to_suid_list = {}
for suid, name in zip(df.index, df['name']):
    try:
        name = int(name)  # Attempt to convert the name to an integer.
    except ValueError:
        pass  # If conversion fails, keep the name as a string.
    if name not in item_name_to_suid_list:
        item_name_to_suid_list[name] = []  # Initialize the key with an empty list if it doesn't exist.
    item_name_to_suid_list[name].append(suid)  # Add the suid to the list associated with the name.
```

This approach ensures that both integer and string keys are handled correctly, preventing the conflict between the query node and the dictionary.

**Comment by GeneCodeSavvy** [comment]
I'll submit a PR with the changes for your review.

**Comment by bdemchak** [comment]
@GeneCodeSavvy Testing came out just fine ... and now I'm ready to release. Apologies for not noticing this problem in the original release ... I had been away from the test suites for a while, and wasn't looking at their results properly.

For some fun, I can suggest running a workflow as a Jupyter Notebook remotely. The notebook runs in the cloud on Google Colab (with Chrome browser) and Cytoscape runs on your local PC. To try this, start Cytoscape and Chrome on your PC. Inside of Chrome, visit the [Notebook ](https://colab.research.google.com/github/bdemchak/cytoscape-jupyter/blob/main/gangsu/basic%20protocol%201.ipynb) and do Runtime | Run All. If you re-run, be sure to use the Runtime menu item to first disconnect and delete your runtime, and then Run All. If you're interested in finding out more, see [here](https://py4cytoscape.readthedocs.io/en/latest/concepts.html#remote-jupyter-notebooks).

**Comment by GeneCodeSavvy** [comment]
@bdemchak Thanks for the update! Glad to hear the testing went well. No worries about the earlier issue—happens to the best of us. I'll make sure to run the entire test suite before submitting any PR, moving forward

The Jupyter Notebook + Cytoscape workflow is interesting! Appreciate the tip and will check out the link for more details.
